version: "3.9"

######
# core services: activemq, mysqldb, configui, dbdiscauth, redfishread
#
# The core services are started for every profile. Additionally specify the
# profile for any backend databases, or start up a test database with the
# following profiles:
#    - influx-test-db  -->  also starts:
#       - influx-pump
#       - grafana
#    - prometheus-test-db  --> also starts:
#       - prometheus-pump
#       - grafana
#    - influx-pump
#    - prometheus-pump
#    - splunk-pump
#    - elk-pump (currently broken?)
#    - grafana
######

x-env-mysql: &mysql-env
  MYSQL_DATABASE: "telemetrysource_services_db"  #specify configured database name
  MYSQL_USER: "reftools"           #sample reference - specify configured user name
  MYSQL_PASSWORD: "*Ref!**lsq8#v*" #sample reference - specify configured credentials
  MYSQL_HOST: "mysqldb"            #sample reference - specify mysql hostname
  MYSQL_HOST_PORT: "3306"          #sample reference - specify mysql port number

x-env-messagebus: &messagebus-env
  MESSAGEBUS_HOST: activemq      #sample reference - specify messagebus hostname
  MESSAGEBUS_PORT: 61613         #sample reference - specify messagebus port

x-env-influx: &influx-env
  INFLUXDB_SERVER: influx
  INFLUXDB_DB: poweredge_telemetry_metrics
  INFLUXDB_URL: http://influxdb:8086

x-arg-base: &base-args
  USER_ID: ${USER_ID:-0}
  GROUP_ID: ${GROUP_ID:-0}
  USERNAME: telemetry
  GROUPNAME: telemetry

x-build-base: &base-build
    context: .
    dockerfile: distribution/docker/scratch-individual/Dockerfile
    args:
      <<: *base-args

# To disable 'core' services (for testing upper layer stuff one daemon at a
# time), switch the comments so the following statement is commented out and
# the subsequent one is uncommented
x-disable-core: &optional-disable []
#x-disable-core: &optional-disable ["disabled"]

x-refdaemon: &refdaemon
  user: telemetry:telemetry
  build:
    <<: *base-build
  profiles: *optional-disable
  environment:
    <<: *messagebus-env
  depends_on: ["mysqldb", "activemq"]
  networks:
    - private

networks:
  private:
    driver: bridge

volumes:
  influxdb-storage:
  grafana-storage:
  prometheus_data:

services:
  activemq:
    container_name: activemq
    image: rmohr/activemq:5.10.0
    profiles: *optional-disable
    networks:
      - private

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    profiles: *optional-disable
    restart: always
    environment:
      <<: *mysql-env
      # this should only be passed to mysqldb, not needed by other daemons and would be security issue if leaked
      MYSQL_ROOT_PASSWORD: "bananas"   #sample reference - specify configured credentials
    networks:
      - private
    #mount deployed mysql filesystem location for persistance


  configui:
    <<: *refdaemon
    image: idrac-telemetry-reference-tools/configui:latest
    build:
      <<: *base-build
      dockerfile: distribution/docker/scratch-individual/Dockerfile.configui
      args:
        <<: *base-args
        CMD: configui
    environment:
      <<: *mysql-env
      <<: *messagebus-env
      CONFIGUI_HTTP_PORT: 8082       #sample reference - specify web application port
    ports:
      - "8080:8082"


  dbdiscauth:
    <<: *refdaemon
    image: idrac-telemetry-reference-tools/dbdiscauth:latest
    environment:
      <<: *messagebus-env
      <<: *mysql-env
    build:
      <<: *base-build
      args:
        <<: *base-args
        CMD: dbdiscauth


  redfishread:
    <<: *refdaemon
    image: idrac-telemetry-reference-tools/redfishread:latest
    build:
      <<: *base-build
      args:
        <<: *base-args
        CMD: redfishread


  influx:
    ############################################################################
    # INFLUX - start an influx db backend. for testing mostly
    #
    # Add this to your docker-compose cli args:
    #   --profile influx-test-db
    #
    # Starting the 'influx-test-db' profile will automatically start:
    #   - influx pump
    #   - influx test database
    #   - grafana dashboard
    #
    ############################################################################
    container_name: influx
    image: influxdb:1.8
    profiles:
      - influx-test-db
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      <<: *influx-env
      node.name: influx
    networks:
      - private
    healthcheck:
      test: curl http://localhost:8086 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5


  influx-pump-standalone: &influx-pump
    ############################################################################
    # INFLUX PUMP - starts the data pump for influx
    #    This is automatically started with the influx-test-db
    #    Manually start this profile if you want to point to an external server
    #
    # Add this to your docker-compose cli args:
    #   --profile influx-pump
    #
    # If you want to connect to an external influx database, set the following
    # environment variables:
    #
    #  INFLUXDB_SERVER: <hostname-or-ip-of-your-influx-server>
    #  INFLUXDB_DB: <name-of-influx-database>
    #  INFLUXDB_URL: http://influxdb:8086
    #
    ############################################################################
    <<: *refdaemon
    image: idrac-telemetry-reference-tools/influxpump:latest
    environment:
      <<: *messagebus-env
      <<: *influx-env
    profiles:
      - influx-pump
    build:
      <<: *base-build
      args:
        <<: *base-args
        CMD: influxpump

  influx-pump-standalone:
    <<: *influx-pump
    depends_on: ["influx"]
    profiles:
      - influx-test-db

  grafana:
    ############################################################################
    # GRAFANA - graphical dashboard for timeseries
    #    This is automatically started with the influx-test-db
    #    Manually start this if you want to point a grafana dashboard at an
    #      external server
    #
    # Add this to your docker-compose cli args:
    #   --profile grafana
    #
    # If you want to connect to an external influx database, set the following
    # environment variables:
    #
    #  INFLUXDB_SERVER: <hostname-or-ip-of-your-influx-server>
    #  INFLUXDB_DB: <name-of-influx-database>
    #  INFLUXDB_URL: http://influxdb:8086
    #
    ############################################################################

    # grafana runs as root in latest version. *sigh*
    container_name: grafana
    image: grafana/grafana:latest
    profiles:
      - grafana
      - influx-test-db
    depends_on:
      - "influx"
    environment:
      <<: *influx-env
    networks:
      - private


  prometheus:
    ############################################################################
    # PROMETHEUS - test prometheus database
    #    This is automatically started with the prometheus-test-db
    #
    # Add this to your docker-compose cli args:
    #   --profile prometheus-test-db
    #
    # If you want to connect to an external prometheus database,
    # set the following environment variables:
    #
    # TODO: add
    #
    ############################################################################
    image: prom/prometheus:v2.1.0
    restart: always
    container_name: prometheus
    profiles:
      - prometheus-test-db
    volumes:
      - type: bind
        source: ${PWD}/cmd/prometheuspump/prometheus.yml
        target: /config/prometheus.yml
        read_only: true
      - prometheus_data:/prometheus
    environment:
      - node.name=prometheus
      - PROMETHEUS_DB=poweredge_telemetry_metrics
    command:
      - '--config.file=/config/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - private


  prometheus-pump-standalone: &prometheus-pump
    ############################################################################
    # PROMETHEUS PUMP - data pump to pump telemetry into prometheus
    #    This is automatically started with the prometheus-test-db
    #    Manually start this profile if you want to point to an external server
    #
    # Add this to your docker-compose cli args:
    #   --profile prometheus-pump
    #
    # If you want to connect to an external prometheus database,
    # set the following environment variables:
    #
    #  PROMETHEUSDB_SERVER: prometheus-hostname
    #
    ############################################################################
    <<: *refdaemon
    image: idrac-telemetry-reference-tools/prometheuspump:latest
    profiles:
      - prometheus-pump
    environment:
      <<: *messagebus-env
      PROMETHEUSDB_SERVER: prometheus
    build:
      <<: *base-build
      args:
        <<: *base-args
        CMD: prometheuspump

  prometheus-pump-withtestserver:
    <<: *prometheus-pump
    depends_on: ["prometheus"]
    profiles:
      - prometheus-test-db

  splunk-pump-standalone:
    ############################################################################
    # SPLUNK PUMP - data pump to pump telemetry into splunk
    #    Manually start this profile if you want to point to an external server
    #
    # Add this to your docker-compose cli args:
    #   --profile splunk-pump
    #
    # If you want to connect to an external splunk database,
    # set the following environment variables:
    #
    # TODO: add
    #
    ############################################################################
    <<: *refdaemon
    image: idrac-telemetry-reference-tools/splunkpump:latest
    profiles:
      - splunk-pump
    build:
      <<: *base-build
      dockerfile: distribution/docker/scratch-individual/Dockerfile.splunkpump
      args:
        <<: *base-args
        CMD: splunkpump

  elk-pump-standalone: &elk-pump
    ############################################################################
    # ELK PUMP - telemetry data pump for elk
    #    Manually start this profile if you want to point to an external server
    #
    # Add this to your docker-compose cli args:
    #   --profile elk-pump
    #
    # If you want to connect to an external ELK instance,
    # set the following environment variables:
    #
    # TODO: add
    #
    ############################################################################
    <<: *refdaemon
    image: idrac-telemetry-reference-tools/elkpump:latest
    profiles:
      - elk-pump
    depends_on:
      - "activemq"
    build:
      <<: *base-build
      args:
        <<: *base-args
        CMD: elkpump-basic

  elk-pump-withtestserver:
    <<: *elk-pump
    profiles:
      - elk-test-db
    environment:
      <<: *messagebus-env
      ELASTICSEARCH_URL: http://es01:9200

  es01:
    ############################################################################
    # ELASTIC SEARCH - test elk instance
    #
    # Add this to your docker-compose cli args:
    #   --profile elk-test-db
    #
    # NOTE: CURRENTLY BROKEN ON INTERNAL DEV SERVERS, CANT TEST:
    #
    #   es02              | ERROR: [1] bootstrap checks failed
    #   es02              | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
    #   es02              | ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/es-docker-cluster.log
    #
    ############################################################################
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es01
    profiles:
      - elk-test-db
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - private

    healthcheck:
      test: curl http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    #mount deployed mysql filesystem location for persistance

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es02
    profiles:
      - elk-test-db
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - private
    #mount deployed mysql filesystem location for persistance

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es03
    profiles:
      - elk-test-db
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - private
    #mount deployed mysql filesystem location for persistance

  kib01:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kib01
    profiles:
      - elk-test-db
    depends_on: ["es01", "es02", "es03"]
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - private
    ports:
      - "5601:5601"


  timescale:
    ############################################################################
    # TIMESCALE - test timescale database
    #    This is automatically started with the timescale-test-db
    #
    # Add this to your docker-compose cli args:
    #   --profile timescale-test-db
    #
    # If you want to connect to an external prometheus database,
    # set the following environment variables:
    #
    # TODO: add
    #
    ############################################################################
    image: timescale/timescaledb:latest-pg12
    container_name: timescale
    profiles:
      - timescale-test-db
    restart: always
    environment:
      - node.name=timescale
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - TIMESCALE_DB=poweredge_telemetry_metrics
    networks:
      - private

  timescale-setup:
    image: timescale/timescaledb:latest-pg12
    restart: "no"
    profiles:
      - timescale-test-db
    depends_on: ["timescale"]
    environment:
      - node.name=timescale
      - POSTGRES_HOST=timescale
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - TIMESCALE_DB=poweredge_telemetry_metrics
    volumes:
      - type: bind
        source: ${PWD}/cmd/initialize_timescaledb.sh
        target: /extrabin/initialize_timescaledb.sh
        read_only: true
    entrypoint: ["/extrabin/initialize_timescaledb.sh"]
    networks:
      - private


  timescale-pump-standalone: &timescale-pump
    ############################################################################
    # TIMESCALE PUMP - telemetry data pump for Timescale
    #    Manually start this profile if you want to point to an external server
    #
    # Add this to your docker-compose cli args:
    #   --profile timescale-pump
    #
    # If you want to connect to an external Timescale instance,
    # set the following environment variables:
    #
    # TODO: add
    #
    ############################################################################
    <<: *refdaemon
    image: idrac-telemetry-reference-tools/timescale-pump:latest
    profiles:
      - timescale-pump
    depends_on:
      - "activemq"
    build:
      <<: *base-build
      args:
        <<: *base-args
        CMD: timescalepump

  timescale-pump-withtestserver:
    <<: *timescale-pump
    profiles:
      - timescale-test-db
    environment:
      <<: *messagebus-env
      POSTGRES_USER: postgres
      POSTGRES_DEFAULT_PWD: postgres
      TIMESCALE_SERVER: timescale
      TIMESCALE_DB: poweredge_telemetry_metrics


# using dbdiscauth for now. dont need simple*
#
#  simpleauth:
#    <<: *refdaemon
#    image: idrac-telemetry-reference-tools/simpleauth:latest
#    build:
#      <<: *base-build
#      args:
#        <<: *base-args
#        CMD: simpleauth
#
#
#  simpledisc:
#    <<: *refdaemon
#    image: idrac-telemetry-reference-tools/simpledisc:latest
#    build:
#      <<: *base-build
#      args:
#        <<: *base-args
#        CMD: simpledisc
